prom-exporter:
  enabled: true
  listen-addr: 0.0.0.0:9044 # listen on all interfaces
influx-db:
  enabled: true
  base-url: "<YOUR INFLUXDB>"
  api-token: "<YOUR API TOKEN>"
  org: "<YOUR ORG>"
  bucket: "<YOUR BUCKET>"
sensor:
  interval: "1m"
  names:
    - "Balcony"
    - "Bath"
    - "Fridge"
